name: MaSuiteChat
main: fi.matiaspaavilainen.masuitechat.bukkit.MaSuiteChat
version: ${project.version}
author: Masagameplay
depend: [Vault, MaSuiteCore]
softdepend: [GriefPrevention, WorldGuard]
commands:
  mail:
    description: Send mail to player
    aliases: [mailplayer, playermail, mailto]