name: MaSuiteChat
main: dev.masa.masuitechat.bukkit.MaSuiteChat
version: ${project.version}
author: Masagameplay
depend: [Vault, MaSuiteCore]
softdepend: [GriefPrevention, WorldGuard]
loadbefore: [Essentials]
api-version: 1.13